### ISSUE TITLE
Bad Interpreter 

### ISSUE THREAD

**Issue by Edwardthedog2** [BukkitPE/Documentation#2]
I'm trying to run a server on a CentOS VPS, but I get this error when I run ./start.sh.
`[edward@edwards-party ~]$ ./start.sh
-bash: ./start.sh: /bin/bash: bad interpreter: Text file busy
`

**Comment by AndreTheGamer** [comment]
@Edwardthedog2  Most likely cause you are using a unsupported bin folder. Make sure you use the correct bin folder for your system. If your system is a 32bit use the 32bit system version. Although if its 64bit use the correct version

**Comment by Edwardthedog2** [comment]
Okay.
